"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Heir_1 = require("./Classes/Heir");
var NobleHouse_1 = require("./Classes/NobleHouse");
var Arryn_1 = require("./Classes/SubClasses/Arryn");
var testHeir = new Heir_1.Heir("test", 18);
var heir2 = new Heir_1.Heir("test2", 17);
var testArryn = new Arryn_1.Arryn("Um falcão branco voando e uma lua crescente em fundo azul escuro", "Casa Arryn", "Tão Alto Como a Honra");
var testHouse = new NobleHouse_1.NobleHouse("testName", "testMotto", "testDescBrasao");
console.log("House> ".concat(testHouse.name, " \nHeir> ").concat(testHeir.heirName));
testHouse.addHeir(testHeir);
testHouse.addHeir(heir2);
testHouse.houseInfo();
console.log(testArryn.soldados);
