"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Book_1 = require("./Classes/Book");
var BookGenre_1 = require("./ENUMs/BookGenre");
var BookStatus_1 = require("./ENUMs/BookStatus");
var Lists2_1 = require("./Classes/Lists2");
var menuMain_1 = require("./menus/menuMain");
var mainMenu = new menuMain_1.menuMain;
var lista = new Lists2_1.Lists2;
var livro = new Book_1.Book("Titulo1", "Autor1");
livro.status = BookStatus_1.BookStatus.Available;
livro.genre = BookGenre_1.BookGenre.genre1;
lista.libraryBooks.push(livro);
livro = new Book_1.Book("Titulo2", "Autor2");
livro.status = BookStatus_1.BookStatus.Available;
livro.genre = BookGenre_1.BookGenre.genre2;
lista.libraryBooks.push(livro);
livro = new Book_1.Book("Titulo3", "Autor3");
livro.status = BookStatus_1.BookStatus.Borrowed;
livro.genre = BookGenre_1.BookGenre.genre4;
lista.libraryBooks.push(livro);
livro = new Book_1.Book("Titulo4", "Autor4");
livro.status = BookStatus_1.BookStatus.Overdue;
livro.genre = BookGenre_1.BookGenre.genre3;
lista.libraryBooks.push(livro);
livro = new Book_1.Book("Titulo5", "Autor5");
livro.status = BookStatus_1.BookStatus.Available;
livro.genre = BookGenre_1.BookGenre.genre5;
lista.libraryBooks.push(livro);
mainMenu.startMenu(lista);
